### ISSUE TITLE
Redis#exists breaking change without major version upgrade

### ISSUE THREAD

**Issue by alber70g** [redis/redis-rb#1071]
Please revert this change, as it's a breaking change in a minor version update: https://github.com/redis/redis-rb/blob/master/CHANGELOG.md#:~:text=Redis%23exists%20now%20returns%20an%20Integer%20by%20default%2C%20as%20warned%20since%204.2.0.%20The%20old%20behavior%20can%20be%20restored%20with%20Redis.exists_returns_integer%20%3D%20false.

https://github.com/redis/redis-rb/pull/1030/

If this is something we want, it should be in a major upgrade.

**Comment by byroot** [comment]
`redis-rb` don't claim SemVer.

**Comment by JoshCheek** [comment]
Most gems don't claim it, because everyone assumes it. Maybe `redis-rb` could make it obvious by giving it a version like `4.5.0.notsemver` or something.

Anyway, given that it doesn't, is there any meaning to any of these three numbers? I assume it's not totally arbitrary, but could not find anything documenting that it's not semver or how to interpret the version numbers. Where I've seen semver not used in the past, it was because the gem's major version tracked the underlying dependency's major version, but `redis-rb` does not appear to do this either.

If anyone has a significant dependency on this gem, to the point that you follow its development, you could make a gem that contains no code, and only has a dependency on this gem, and follows [semver](https://semver.org). So each version would specify only known compatible versions of `redis-rb` in its dependencies, and would make a new release for each of this gem's releases, but its versions would follow semver. Eg when 4.5.0 was released, this gem would make a new major release with a gemspec containing `spec.add_dependency 'redis', '= 4.5.0'` (in this case the constraint must be exactly that version b/c it is not compatible with previous ones, and it is not yet known whether it is compatible with future ones). Then we could specify a dependency on that gem instead, and let it specify which versions of `redis-rb` that translates to. If you're already following the development, then this would only a small amount of additional work.
