### ISSUE TITLE
Upgrading from 4.8.0 to 5.0.0 breaks ActionCable?

### ISSUE THREAD

**Issue by evaneykelen** [redis/redis-rb#1141]
Gemfile.lock before upgrade:
* redis (4.8.0)

After upgrade:
* connection_pool (2.2.5)
* redis (5.0.0)
  * redis-client (~> 0.7)
* redis-client (0.7.1)
  * connection_pool

After upgrading redis to 5.0.0, Rails starts to throw the following exception:

`Gem::LoadError: Error loading the 'redis' Action Cable pubsub adapter. Missing a gem it depends on? can't activate redis (>= 3, < 5), already activated redis-5.0.0. Make sure all dependencies are added to Gemfile.`

**Comment by byroot** [comment]
Yes, currently `actioncable 7.0.3.1` won't load if you upgrade. 

But I made it compatible recently, and if you point your Gemfile to the `7-0-stable` branch on Rails it will work:

```ruby
gem "rails", github: "rails/rails", branch: "7-0-stable"
```

Or you can wait for `7.0.4` to be released (no idea when).

Sorry you encountered this issue, but since redis is an optional dependency, there's no way to handle this better.

Also anyone having the same issue with RedisCacheStore in Active Support, the solution is the same.

**Comment by evaneykelen** [comment]
Thanks @byroot, a dug a bit deeper and indeed found the relevant counterpart issue here: https://github.com/rails/rails/pull/45856. I'll take the 7-0-stable route for now!
