### ISSUE TITLE
In hmset method in Redis::Commands::Hashes module, would be good show warning message if attr value is ambiguous

### ISSUE THREAD

**Issue by roharon** [redis/redis-rb#1161]
In `hmset` method in `lib/redis/commands/hashes.rb`

We can using it like
```ruby
Redis.new.hmset('key', 'a', '2', '3', '4')
# "HMSET" "key" "1" "2" "3" "4"

# 127.0.0.1:6379> hgetall key
# 1) "1"
# 2) "2"
# 3) "3"
# 4) "4"
```

But in this case, I think this `hmset` command working is pretty ambiguous.
```ruby
Redis.new.hmset("key", 'a', ['2', '3', '4'])
# "HMSET" "key" "2" "3" "4"

# I think would be works like 
# "HMSET" "key" "['2', '3', '4']"
# 127.0.0.1:6379> hgetall key
# 1) "['2' ,'3', '4']"
```

When we execute `hmset('key, 'a', '2', '3', '4')`, it called `send_command ([:hmset, \"key\", \"a\", 1, 2, 3]")`.
But, `hmset('key, 'a', ['2', '3', '4'])` called `send_command ([:hmset, \"key\", \"a\", [1, 2, 3]]")` that parameter consist of string and nested array
```ruby
   def hmset(key, *attrs)
        send_command([:hmset, key] + attrs)
   end
```

I think it should be raise `RedisClient::WrongTypeError` or show warning message if `attr` variable is ambiguous(that consist of nested array)

**Comment by byroot** [comment]
It's really unclear what this issue is about.

```
Redis.new.hmset("key", 'a', ['2', '3', '4'])
# "HMSET" "key" "2" "3" "4"
```

That's incorrect, I get:

```
# "HMSET" "key" "a", "2" "3" "4"
```

Which is correct to me.


> When we execute hmset('key, 'a', '2', '3', '4'), it called send_command ([:hmset, \"key\", \"a\", 1, 2, 3]").

Not correct either.

> I think it should be raise RedisClient::WrongTypeError 

`WrongTypeError` maps to an error sent by the server. If we wanted to raise on this it would be a regular `TypeError`.

But I disagree this is a bug. Variadic commands accept vargars and arrays for convenience as there's no point splatting an array and for large arrays it might cause a stack overflow.

We could raise an error if you mix both, but I don't really see the point.

**Comment by roharon** [comment]
I see.
and I edited the incorrect example
