### ISSUE TITLE
Feature request: server assisted client side caching

### ISSUE THREAD

**Issue by mbyio** [redis/redis-rb#1301]
Python recently got support for client side caching. It would be nice if Ruby could do it too.

Question - would client side caching be best implemented in `redis-client`?

**Comment by byroot** [comment]
> It would be nice if Ruby could do it too.

I honestly don't really see the point. In Ruby because of the GVL you'll likely have one process per core, so that's as many small "buckets" that will need to cache the same thing multiple times.

Then since Ruby GC is generational, keeping in memory cache will cause objects to be promoted and to require a major GC cycle to be reclaimed, which is really bad for tail latency.

IMO this can only be efficiently implemented as a sidecar proxy.

All this to say, I have zero intention to work on it, but if someone comes up with a PR that doesn't add too much complexity, then I'll consider merging it.

> would client side caching be best implemented in redis-client?

Probably, not sure.

**Comment by mbyio** [comment]
Thanks, I appreciate the response. I have to respectfully disagree with most of your points, although I don't expect to change your mind. I will leave my viewpoint for the record here.

In both Python (before they removed the GIL) and Ruby, I've had great success using a pull-through in-memory cache in large web services. The main advantages are lower latency and lower load on the Redis servers. We already have layers of caching higher up the stack (eg. in the CDN, and the user web browser) so it makes a lot of sense to have a layer of caching in our Ruby pods too.

The advantage of using Redis' built-in cache invalidation is we can raise the TTL for the in-memory cache much higher, because we would be proactively notified when the cache is invalidated in the Redis server. This is especially helpful when using Redis as the source of truth for your data (like for sorted sets).

> In Ruby because of the GVL you'll likely have one process per core, so that's as many small "buckets" that will need to cache the same thing multiple times.

This is true, we currently keep an in-memory cache per core. For us, RAM is much cheaper than CPU, so it is an acceptable tradeoff.

> Then since Ruby GC is generational, keeping in memory cache will cause objects to be promoted and to require a major GC cycle to be reclaimed, which is really bad for tail latency.

I haven't seen this issue, but I'm sure this depends on the application and how much load you put on the GC.

> IMO this can only be efficiently implemented as a sidecar proxy.

I agree that a sidecar proxy could be more efficient, although we would still have to do IPC to get data from the proxy and also deploy another component. Depending on one's goals, I think it may not actually be that much better.
