### ISSUE TITLE
Support for Staggered Cache Refresh with Dual Redis Servers

### ISSUE THREAD

**Issue by rohangrg** [redis/redis-rb#1305]
**Problem Statement:**

In my Rails application, I often deal with expensive computations that take significant time to generate. To optimize performance and ensure high availability during recomputations (in case of forced cache clear), I want to maintain two Redis servers that serve different roles:

- **Primary Redis**: Used for recomputing and storing the latest values.
- **Secondary Redis**: Acts as a fallback to serve stale values while the recomputation is in progress.

**The proposed workflow is as follows:**

- Step 1: A value is computed and cached in both Redis servers.
- Step 2: When the value needs to be recomputed:
    - The key is deleted from the Primary Redis.
    - The recomputation process begins in the background.
    - Meanwhile, the Secondary Redis serves the older (stale) value to any incoming requests.
- Step 3: Once the recomputation is complete, the updated value is written to the Primary Redis and synchronized to the Secondary Redis.

**Additional Notes**

- This may not be as useful for large companies with sophisticated caching strategies, but for startups that rely heavily on caching for performance, it can be a **gold mine**.
- Can anyone else validate this idea and share their thoughts on its feasibility?
- I am happy to contribute to this if others find it useful or feasible!

**Comment by byroot** [comment]
> * share their thoughts on its feasibility?

I don't think that's something feasible at the client level (without touching on whether it would be desirable) because the sheer amount of different commands to handle etc.

Also things like:

> The recomputation process begins in the background.

Aren't well suited for low level libraries. As soon as you get notions of "background" work, it's up to the application to define how concurrency/parallelism happen, there's nothing worse than a library that spawns unmanaged threads for you.

It would be way easier to implement what you have in mind as a smaller library with a reduced API.
