### ISSUE TITLE
ignores password in REDIS_URL

### ISSUE THREAD

**Issue by odigity** [redis/redis-rb#460]
I have redis 2.8.4 on one host, and redis gem 3.1.0 in a Rails 4.1.4 app on a second host.  I've set REDIS_URL in the env of the Rails app, and can connect via the Rails console with "Redis.new".

I then added a password to the redis server, restarted it, and added the password to the REDIS_URL value, but got an error when trying to connect:

"Redis::CommandError: NOAUTH Authentication required."

However, it does work if I take the password out of REDIS_URL and use the more eplicit constructor:

"Redis.new(password: 'foo')"

FYI-This matters because I don't explicitly create the Redis connection, that's done by Sidekiq, so I don't have the option of explicitly passing in the password to the initializer.  There might be a hook in Sidekiq to do it, but it'd be nice to not have to go through that...

**Comment by zeltice** [comment]
I'm still seeing this problem on my end.

Delete your ENV["REDIS_URL"]  and ENV["REDIS_PROVIDER"] from your environment settings, and sidekiq will fail to boot due to NOAUTH redis error (if you have redis set using a password).

It does not matter what you put in your Rails initializer's Sidekiq.configure_client do |config| .... end.  It seems all of that is ignored because code in:

https://github.com/mperham/sidekiq/blob/2fc1d81cc9691c9232a088f1410c5a27fae5e11f/lib/sidekiq/redis_connection.rb  line 72 takes precedence over all.

**Comment by yaauie** [comment]
@zeltice: this issue is closed because we have validated that the redis ruby adapter correctly handles auth when instantiated with a Basic Auth-style URL; if you have a problem with how a different library (e.g., [mperham/sidekiq](https://github.com/mperham/sidekiq)) *uses* the redis ruby adapter, you'll be better off opening an issue on that project where someone can help.

**Comment by bf4** [comment]
@zeltice Have you opened an issue in Sidekiq? fwiw, I see in the code you linked that it only falls back on the ENV if `url` isn't passed in `options[:url] ||= determine_redis_provider`. I'll work on it there with you if you'd like
