### ISSUE TITLE
ruby 2.1.0 crashes when using a client initialised with options

### ISSUE THREAD

**Issue by weemaels** [redis/redis-rb#479]
require 'redis'
Redis.new(host: 'localhost').ping

When redis is not running on localhost, the code above makes ruby 2.1.0 abort.

Using the initialiser without options, raises the expected exception:
Redis.new.ping

**Comment by cindyward1** [comment]
This is still a problem with localhost, Ruby 2.2.1 and OS X 10.9.5 (Mavericks). I had to restrict redis to ~>2.0 which meant I had to restrict resque to ~>1.23. I don't expect you to reopen the issue, I just want to document that whatever this problem is, it is not fixed in Ruby 2.2.1 and it affects OS X versions less than Yosemite.

**Comment by yaauie** [comment]
@cindyward1 There are other routes to your local host than the named alias `localhost`, which on your machine is resolving via IPv6 & causing the issue; `127.0.0.1` & `0.0.0.0` are generally acceptable IPv4 alternatives on a Mac (& other platforms too)
