### ISSUE TITLE
Using SORT on read-only slave.

### ISSUE THREAD

**Issue by nopc0de** [redis/redis-rb#525]
I can't sort on a read-only slave (anymore).

```
~/.gem/ruby/2.1.3/gems/redis-3.2.1/lib/redis/client.rb:113:in `call': READONLY You can't write against a read only slave. (Redis::CommandError)
	from ~/.gem/ruby/2.1.3/gems/redis-3.2.1/lib/redis.rb:557:in `block in sort'
	from ~/.gem/ruby/2.1.3/gems/redis-3.2.1/lib/redis.rb:37:in `block in synchronize'
	from ~/.rubies/ruby-2.1.3/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
	from ~/.gem/ruby/2.1.3/gems/redis-3.2.1/lib/redis.rb:37:in `synchronize'
	from ~/.gem/ruby/2.1.3/gems/redis-3.2.1/lib/redis.rb:556:in `sort'
```

I'm now using `redis.smembers("key").sort` instead.

**Comment by badboy** [comment]
Yep, the `SORT` command is [marked a write command](https://github.com/antirez/redis/blob/3.0/src/redis.c#L243), due to its [`STORE` option](http://redis.io/commands/sort#storing-the-result-of-a-sort-operation). Whether or not a command writes is determined before it is executed (and all additional arguments are parsed), that's why, with the current design, it's not possible to distinguish between `SORT` being read-only or writing.

**Comment by amree** [comment]
Sorry for asking in an old issue but I thought it's ok since it's highly related.

May I know if we can run something like `redis.sort_ro` on the replicas? It doesn't seem to be supported based on the code

https://github.com/redis/redis-rb/blob/2b183addb9175641a48e1d8616772282a31c0532/lib/redis/commands/keys.rb#L389

But asking here for confirmation
