### ISSUE TITLE
Increment Redis::CommandError: ERR value is not an integer or out of range 

### ISSUE THREAD

**Issue by raldred** [redis/redis-rb#532]
Hey I'm using redis with Rails via the redis-rails gem.
My project uses redis v3.1.0 with Redis Cloud on Heroku cedar-10.

I'm setting up a basic counter
`Rails.cache.write("warmingstage_4_counter", 0)`

then calling

`Rails.cache.increment("warmingstage_4_counter")` raises the exception
`Redis::CommandError: ERR value is not an integer or out of range`

I can't find any other reports of this issue for this or any of the associated redis-rails gems.
Would this be fixed if i were to use 3.2.1?

Thanks for your time.

**Comment by badboy** [comment]
I never used ActiveSupport::Cache myself, but I took a quick look at the code and it seems that by default it encodes the value. So even if you put in `0` this is not purely what ends up in the cache, and that's why the increment fails. There is an option to write the raw value though, check the documentation again.

**Comment by raldred** [comment]
Thanks for the rapid response @badboy 
I really should RTFM.
You're absolutely right.
`Rails.cache.write("warmingstage_4_counter", 0, raw: true)`
