### ISSUE TITLE
Problem with multithreading

### ISSUE THREAD

**Issue by digininja** [redis/redis-rb#582]
I'm working on an app running in Jruby that uses code similar to this:

```ruby
require "redis"
require "concurrent"

redis = Redis.new
redis.flushdb

pool = Concurrent::FixedThreadPool.new(Concurrent.processor_count)
1.upto 2000000 do |i|
        pool.post do
                redis.zincrby("lengths", 1, Random.rand(10))
        end
end
```
The increase works fine and the final totals are correct but this running it eats memory very quickly. From jmap I get the following

```
 num     #instances         #bytes  class name
----------------------------------------------
   1:        922680       44288640  org.jruby.RubyArray
   2:        922400       44275200  org.jruby.runtime.Binding
   3:        922985       36919400  org.jruby.RubyFixnum
   4:        922400       36896000  org.jruby.runtime.Block
   5:        922338       36893520  org.jruby.RubyProc
```

Which suggests something in the gem isn't getting cleared down after the zincrby and so things are just stacking up. If I run the same loop with a puts, or even storing the results in memory, these entries don't appear so it is definitely something to do with Redis.

Is this something I'm doing wrong, a bug or a known issue?

**Comment by chrisseaton** [comment]
You're creating 2,000,000 tasks there, which means allocating 2 million procs, capturing 2 million local environments etc etc. So that's simply quite a lot of objects to create. The number of bytes you've got allocated looks like a lot, but it's only 22 bytes per task when you divide it out.

You may want to change your architecture a bit here. Do you need to create 2 million concurrent tasks at the same time when you only have perhaps 4 or 8 cores? Even if you are doing this to exploit IO concurrency, the VM is unlikely to successfuly schedule 2 million IO tasks at the same time.

Does that make sense? If it does we can think about how to restructure this a bit.

**Comment by digininja** [comment]
I thought initialising the pool with the processor count would limit it to
that many running tasks. Am I wrong on that?

**Comment by chrisseaton** [comment]
Yes it is limiting to that number of concurrently running tasks - that's correct and you're using `Concurrent.processor_count` correctly for a processor-bound application.

However, you are adding the 2 million tasks to the pool, even if it's only running say 4 concurrently. They sit in the queue waiting to run, but also taking up memory. It's a bit like you're doing this:

```ruby
tasks = []
1.upto 2000000 do |i|
        tasks << proc do
                redis.zincrby("lengths", 1, Random.rand(10))
        end
end
# Start to take up to 4 tasks at a time from tasks and run them concurrently
```

So your 2 million procs sit around taking up space. That's where your memory use is coming from.

**Comment by digininja** [comment]
I'll close this as it isn't a Redis problem, its me not understanding threading properly.
