### ISSUE TITLE
Ability to have multiple "current" instances

### ISSUE THREAD

**Issue by tomprats** [redis/redis-rb#605]
I have an application that works with 2 completely independent Redis servers, right now we're using global variables, but I discovered the `Redis.current` functionality. It seems we could switch one to use that, but then the other would still be a global variable.

It would be great if there were a way to define something `Redis.current_cats` and `Redis.current_dogs`. Not a big issue to continue as it is, but I just thought I'd give my 2 cents

**Comment by badboy** [comment]
Sounds like a bad idea to me. `current` is a convenience feature and yet nothing different from having your own global. If you absolutely have to you can monkey-patch your `current_cats` and `current_dogs` into the Redis class.

**Comment by djanowski** [comment]
Agree with Jan-Erik, Redis.current is there mostly so that other libraries
that use Redis can grab the default connection to it. In your case it makes
perfect sense to use global variables. Thanks
On Apr 8, 2016 06:28, "Jan-Erik Rediger" <notifications@github.com> wrote:

Sounds like a bad idea to me. current is a convenience feature and yet
nothing different from having your own global. If you absolutely have to
you can monkey-patch your current_cats and current_dogs into the Redis
class.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/redis/redis-rb/issues/605#issuecomment-207347442>

**Comment by tomprats** [comment]
Definitely makes sense, thanks for taking a look at it
