### ISSUE TITLE
Get original TTL / Expiration time

### ISSUE THREAD

**Issue by marcosanfilippo** [redis/redis-rb#695]
As explained in 
*https://github.com/antirez/redis/blob/unstable/src/db.c#L513*

Redis converts the original TTL in Unix Timestamp. 
So, Redis cannot return the TTL we specify, simply because it does not store it in that format.
How can we add a TTL "meta field", if it is important for the application?

I need to get the original TTL. Thanks

**Comment by badboy** [comment]
The link you used points to some random code line. Please use commit-bound URLs when linking to code (press `y` when on any file on GitHub to get a URL containing the full commit hash).

As you mentioned yourself: Redis does not store it. If you need it, it is up to you to store it besides your data. How you want to do that is totally up for you, e.g. as an additional key, an additional field in a hash or otherwise encoded in your data. It's not the task of redis-rb to keep track of this.
