### ISSUE TITLE
Changelog is incomplete

### ISSUE THREAD

**Issue by joelpresence** [redis/redis-rb#743]
Thanks for all of your hard work on this gem!

It looks like there are no changelog entries for 3.3.5 or 3.3.4 even though they were released to rubygems.  Due to an issue with resque, we need to downgrade below 4.0.0 (`Resque.connect` issues) so I'd rather not downgrade to a version of the `redis` gem that doesn't have a changelog entry.  That would leave me with 3.3.3 but I'd rather use 3.3.5 if possible, but no changelog entry, so not clear if it's a "safe" version?  :-)

**Comment by axelson** [comment]
@joelpresence it looks like the changelog on master never got changes merged from the 3.3 branch. If you view the changelog on 3.3 you can see entries for 3.3.4 and 3.3.5: https://github.com/redis/redis-rb/blob/3.3/CHANGELOG.md

Also the changelog doesn't mention it but 3.3.4 was yanked because it silently dropped support for Ruby 1.8: https://github.com/redis/redis-rb/issues/719

Here is the commit with the main change between 3.3.3 and 3.3.5. Doesn't seem like something you really need except in preparation for the breaking (I think) changes in 4.0: https://github.com/redis/redis-rb/commit/07d04dee5e822364e47501dc68b8a71dd9cd833c

**Comment by byroot** [comment]
Fixed in https://github.com/redis/redis-rb/commit/6f3510e4bd08aea52576d534b5376fa2396f9d35

Thanks @axelson

**Comment by axelson** [comment]
@byroot thanks for fixing!
