### ISSUE TITLE
Looks like subscribe_with_timeout is not thread safe

### ISSUE THREAD

**Issue by prateek-rg** [redis/redis-rb#748]
We are using redis pub/sub with sidekiq.
We are using subscribe_with_timeout to subscribe to messages.
We are facing a weird issue where:-
1. PUB/SUB is working fine with concurrency on 1, but when we increase the concurrency, for some of the messages, the subscriber is not being hit.
2. We have put a timeout of 300 seconds in the subscribe_with_timeout method, however, when the subscriber is not hit, the timeout is being hit after 300*concurrency seconds.

We tried the same with subscribe instead of subscribe_with_timeout and everything worked fine.
This is a big issue for us as it will increase our infra cost 3 times to support similar load.

**Comment by byroot** [comment]
Please provide a reproduction script, otherwise it's close to impossible to understand your issue.

I highly suspect you are using a single Redis connection object with multiple threads, hence all your threads but one are waiting on a mutex.

The correct way to do this is to have one connection per thread.

However if I'm wrong and you provide a repro script I'll look into.
