### ISSUE TITLE
Can I help?

### ISSUE THREAD

**Issue by mperham** [redis/redis-rb#752]
Looks like this repo is struggling with support.  I would be happy to provide some maintenance / support for issues/PRs.  Interested?

**Comment by djanowski** [comment]
I understand @badboy added more collaborators recently. What's the status of that, Jan-Erik?

**Comment by badboy** [comment]
I haven't done so! Will do that on the weekend.

**Comment by badboy** [comment]
I just added a bunch of Shopify folks as admins to this repo (through the redis-rb team):

@fw42 
@sirupsen
@rafaelfranca
@dylanahsmith
@csfrancis
@byroot

I will also add them as collaborators on hiredis-rb and to Rubygems.

Please coordinate ongoing work, don't remove folks and keep hacking!

**Comment by fw42** [comment]
Danke Jan-Erik!

**Comment by byroot** [comment]
Thanks @badboy, we'll do our best.

However if @mperham propose to step in, I think he would be very helpful person for this repo (if not more than us shopifolks).

**Comment by tubbo** [comment]
I can also help, currently maintaining the redis-store gems and I've seen more than one place where some collaboration between us could really clean up some ugly code. will continue to monitor issues and contribute where I can.

**Comment by whatl3y** [comment]
In addition to better support, I would love the latest updates be published to rubygems. I struggled for a while on trying to get the SSLContext verify_mode == `VERIFY_NONE` since I was connecting via the redis server's IP address, but realized after hours of trying, asking a stack overflow question, and opening a forum discussion in AWS with little help that the commit I needed wasn't up yet: https://github.com/redis/redis-rb/commit/25f1f705e0afb9942b2303799f4da156173e05ab

I am working around this by updating by Gemfile to be the following, but for obvious reasons would like to avoid this if possible in the future:

`gem "redis", :git => 'git://github.com/redis/redis-rb'`

**Comment by byroot** [comment]
> I would love the latest updates be published to rubygems.

I'd love to as well, unfortunately I still don't have publish access on rubygems. I was traveling the last few week, but I'll try to get them.

@badboy if you ear us I'd love to push a new version out

Also cc @fw42

**Comment by badboy** [comment]
And it's done (added the list of emails I got a while back from @fw42). Thanks for maintaining this and sorry for the delay.
