### ISSUE TITLE
Redis 4.0 does not support #[] and #[]= methods

### ISSUE THREAD

**Issue by hananamar** [redis/redis-rb#825]
The `#[]` and `#[]=` aliases for `#get` and `#set` have been removed in version 4.0.

This is unfortunate, since the `#[]` and `#[]=` getter and setter are required in order to use Redis as a KeyValue backend for Rails' I18n module.
See [the documentation for `I18n::Backend::KeyValue`](https://www.rubydoc.info/github/svenfuchs/i18n/master/I18n/Backend/KeyValue).

Can anyone say why they were removed, and whether they could be re-introduced?

**Comment by tubbo** [comment]
There’s an i18n backend for redis called redis-i18n, I don’t think the hash-like getter/setter methods are required for i18n backend compatibility...
  

  
  

  
>

**Comment by byroot** [comment]
Agreed. I see how `#[]` and `#[]=` might have been convenient, but IMO it's much better to use a wrapper so that you can handle prefixes and such.

**Comment by hananamar** [comment]
I see. Thanks.

**Comment by TALlama** [comment]
This is not as simple as "just use `redis-i18n`", because trying to include both of the `redis` and `redis-i18n` gems will result in this failure on Rails startup:

```
...gems/redis-i18n-0.0.0/lib/redis-i18n/version.rb:1:in `<main>': Redis is not a module (TypeError)
```

In other words, if you want to use the built-in Rails redis cache store (which requires `redis >= 4`), you cannot use `redis-i18n`, so you have to find another way to back your i18n. It is therefore very problematic that the adapter that used to supports that setup no longer works.

I think this issue should be re-opened; it's not just that `#[]` and `#[]=` were convenient; it's that they allowed redis-backed locales, and at present there's no good way to replace that functionality.

**Comment by tubbo** [comment]
@TALlama that's somewhat of a common issue with redis-i18n if you don't include other redis-store libraries as well. it's just because bundler can't figure out the right version so it uses a really old one that has `module Redis` somewhere in the code, causing the error you just experienced. You can solve it by having `gem 'redis-store', '~> 1.6'` in Gemfile for now, but I'm still trying to track down how to prevent it from happening in the future.
